config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :jokes

  root 'jokes#welcome'

end

app/models/joke.rb
class Joke < ActiveRecord::Base
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jokes_controller.rb
class JokesController < ApplicationController
  before_action :set_joke, only: [:show, :edit, :update, :destroy]

  # GET /jokes
  # GET /jokes.json
  def index
    @jokes = Joke.all
  end

  # GET /jokes/1
  # GET /jokes/1.json
  def show
    @jokes = Joke.first
    @next_joke = Joke.all.sample
    @next_quote = Quote.all.sample
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit
  end
  
  def welcome
    @joke = Joke.first
    @next_joke = Joke.all.sample
    @next_quote = Quote.all.sample
  end

  # POST /jokes
  # POST /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to new_joke_path, notice: 'Joke was successfully created.' }
        format.json { render :show, status: :created, location: @joke }
      else
        format.html { render :new, notice: 'Didnt save try again' }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1
  # PATCH/PUT /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to @joke, notice: 'Joke was successfully updated.' }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1
  # DELETE /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_url, notice: 'Joke was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_joke
      @joke = Joke.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def joke_params
      params.require(:joke).permit(:setup, :punchline)
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quotes = Quote.first
    @next_quote = Quote.all.sample
    @next_joke = Joke.all.sample
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:saying, :source)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jokes_helper.rb
module JokesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/jokes/_form.html.erb
<%= form_for(@joke) do |f| %>
  <% if @joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
      <% @joke.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :setup %><br>
    <%= f.text_area :setup %>
  </div>
  <div class="field">
    <%= f.label :punchline %><br>
    <%= f.text_area :punchline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<h1>Editing Joke</h1>

<%= render 'form' %>

<%= link_to 'Show', @joke %> |
<%= link_to 'Back', jokes_path %>

app/views/jokes/index.html.erb
<% @jokes.each do |joke| %>
  
    <p><%= joke.setup %> <%= joke.punchline %></p>
<% end %>

<%= render partial: 'shared/buttons' %>

app/views/jokes/new.html.erb
<p id="notice"><%= notice %></p>

<h1>New Joke</h1>

<%= render 'form' %>

<%= link_to 'Back', jokes_path %>

app/views/jokes/show.html.erb
<p>
  <%= @joke.setup %> <%= @joke.punchline %>
</p>

<%= render partial: 'shared/buttons', :locals => { :next_joke => @next_joke, :next_quote => @next_quote} %>

app/views/jokes/welcome.html.erb
<%= render partial: 'shared/buttons', :locals => {:next_joke => @next_joke, :next_quote => @next_quote} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :saying %><br>
    <%= f.text_area :saying %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Saying</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.saying %></td>
        <td><%= quote.source %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p>

  <%= @quote.saying %><%= @quote.source %>
</p>

<%= render partial: 'shared/buttons', :locals => { :next_quote => @next_quote, :next_joke => @next_joke} %>

app/views/shared/_buttons.html.erb
<%= button_to 'jokes', joke_path(next_joke), method: "get" %>
<%= button_to 'pearls of wisdom', quote_path(next_quote), method: "get" %>